name: agent-eval-sample
version: "0.1-dev"

splits:
  - name: validation
    tasks:
      - name: first_task
        path: tasks/first_task
        primary_metric: 'my_scorer/my_metric'
        tags:
          - category1

  - name: test
    tasks:
      - name: second_task
        path: tasks/second_task
        primary_metric: 'my_scorer/mean'
        tags:
          - category2

    macro_average_weight_adjustments:
      - tag: category2
        task: second_task
        weight: 0.5  # any other tasks not specified will default to 1.0
