name: Validate dataset_features.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -e .

      - name: Check if schema is up to date
        run: python scripts/update_schema.py --check

